### ISSUE TITLE
The link on README direct to a 404 web page

### ISSUE THREAD

**Issue by h3ndry** [PacktPublishing/The-Modern-Cpp-Challenge#7]
_This is the code repository for The Modern C++ Challenge, published by Packt. It contains all the supporting project files necessary to work through the book from start to finish._

first link from this paragraph direct to an 404 page

**Comment by shruthis-shetty** [comment]
Hi @h3ndry, are you talking about the Readme.md file present in the code section of Github repo?

**Comment by shruthis-shetty** [comment]
I hope the issue got solved now. 

Thanks for noticing this, @h3ndry.
